logging:
  level:
    org.springframework: ERROR
    org.mongodb: ERROR
    com.zaxxer.hikari: ERROR
    org.hibernate.cfg: ERROR
    org.hibernate.boot: ERROR
    org.hibernate.type: ERROR
    org.hibernate.hql: ERROR
    org.hibernate.internal: ERROR
    org.hibernate.query: ERROR
    org.hibernate.loader: ERROR 
    org.hibernate.stat: ERROR
    org.hibernate.secure: ERROR
    o.h.service.internal: ERROR
   
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/fairy-pro?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username : fairy-pro
    password : fairy-pro
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
snowflake:
   workerId: 0
   dataCenterId: 0
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: fairy-pro
